#!/usr/bin/env bash

if ! command -v nix > /dev/null; then
	return
fi

nix_direnv="$(nix eval --raw -f '<nixpkgs>' nix-direnv.outPath)"
nix_direnvrc="$nix_direnv/share/nix-direnv/direnvrc"

if [ -f "$nix_direnvrc" ]; then
	echo "direnv: using $nix_direnvrc"
	. "$nix_direnvrc"
fi
