#!/usr/bin/env bash

# Check if Nix is available
if ! command -v nix > /dev/null; then
	return
fi

# Check if nix-direnv is available
nix_direnvrc=$(readlink -e "$HOME/.nix-profile/share/nix-direnv/direnvrc")
if ! [ -f "$nix_direnvrc" ]; then
	return
fi

# https://github.com/nix-community/nix-direnv#storing-direnv-outside-the-project-directory
: ${XDG_CACHE_HOME:=$HOME/.cache}
declare -A direnv_layout_dirs
direnv_layout_dir() {
	echo "${direnv_layout_dirs[$PWD]:=$(
		echo -n "$XDG_CACHE_HOME/direnv/layouts/$(systemd-escape -p "$PWD")"
	)}"
}
mkdir -p "$XDG_CACHE_HOME/direnv/layouts/"

echo "direnv: using $nix_direnvrc"
. "$nix_direnvrc"
