#!/bin/sh

run_once() {
    if ! pgrep -f -x "$1" > /dev/null; then
        echo "Starting $1"
        $1 &
    else
        echo "$1 is already running"
    fi
}

bspc rule -r "*"

run_once "sxhkd"
run_once "dunst"
run_once "xscreensaver -nosplash"
if systemctl is-active --quiet NetworkManager.service 2> /dev/null; then
    run_once "nm-applet"
fi
run_once "dropbox start"
run_once "xrdb ${HOME}/.Xresources"
run_once "setxkbmap us altgr-intl"
run_once "xmodmap ${HOME}/.Xmodmap"
run_once "xsetroot -cursor_name left_ptr"

# Monitor setup
. ~/.config/bspwm/monitor.sh

# Enable window swallowing
. ~/.config/bspwm/swallow.sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 19

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#fabd2f"
bspc config urgent_border_color "#fb4934"

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a zoom state=floating
bspc rule -a uniselect state=floating

if [ -f "${XDG_CONFIG_HOME:-${HOME}/.config}/awesome/backgrounds/Wallpaper.jpg" ]; then
	feh --no-fehbg --bg-fill "${XDG_CONFIG_HOME:-${HOME}/.config}/awesome/backgrounds/Wallpaper.jpg"
fi

if [ -f "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/bspwmrc.local" ]; then
	. "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/bspwmrc.local"
fi
